//
// DefaultAPI.swift
//
// Generated by swagger-codegen
// https://github.com/swagger-api/swagger-codegen
//

import Foundation
import Alamofire



open class DefaultAPI {
    /**
     Returns a user by ID.
     
     - parameter userId: (path) The ID of the user to return. 
     - parameter completion: completion handler to receive the data and the error objects
     */
    open class func userUserIdGet(userId: String, completion: @escaping ((_ data: UserResponse?,_ error: Error?) -> Void)) {
        userUserIdGetWithRequestBuilder(userId: userId).execute { (response, error) -> Void in
            completion(response?.body, error);
        }
    }


    /**
     Returns a user by ID.
     - GET /user/{userId}
     - examples: [{contentType=Success, example={
  "result" : "SUCCESS"
}}]
     
     - parameter userId: (path) The ID of the user to return. 

     - returns: RequestBuilder<UserResponse> 
     */
    open class func userUserIdGetWithRequestBuilder(userId: String) -> RequestBuilder<UserResponse> {
        var path = "/user/{userId}"
        path = path.replacingOccurrences(of: "{userId}", with: "\(userId)", options: .literal, range: nil)
        let URLString = SylviaExampleClientAPI.basePath + path
        let parameters: [String:Any]? = nil

        let url = NSURLComponents(string: URLString)


        let requestBuilder: RequestBuilder<UserResponse>.Type = SylviaExampleClientAPI.requestBuilderFactory.getBuilder()

        return requestBuilder.init(method: "GET", URLString: (url?.string ?? URLString), parameters: parameters, isBody: false)
    }

}
